# Generated by Django 4.1.3 on 2022-11-28 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tarefa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='user',
            new_name='disciplina',
        ),
    ]
