# Generated by Django 4.1.3 on 2022-11-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_user_tarefa_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
