# Generated by Django 4.1.3 on 2022-11-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_disciplina_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
