# Generated by Django 4.1.3 on 2022-11-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_disciplina_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='description',
        ),
    ]
